import { BrainV2Context, BrainV2Domain, BrainV2Input, BrainV2Intent, BrainV2Urgency } from "./BrainTypes";
export class BrainV2ContextEngine {
 readonly id="brain-v2-context-engine"; readonly version="2.0.0";
 analyze(input:BrainV2Input):BrainV2Context { const message=input.message.trim(); const normalized=this.normalize(message); const intent=this.detectIntent(normalized); const domains=this.detectDomains(normalized); const urgency=this.detectUrgency(normalized); return {message, normalizedMessage:normalized, intent, domains, urgency, confidence:this.confidence(intent,domains), detectedDates:this.detectDates(message), keywords:this.extractKeywords(normalized), needsPlanning:["plan","schedule","project"].includes(intent), needsDecision:intent==="decision"||normalized.includes("choisir")||normalized.includes("meilleur"), needsGoal:["goal","project"].includes(intent)||normalized.includes("objectif"), createdAt:new Date().toISOString()}; }
 private normalize(v:string){ return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim(); }
 private detectIntent(t:string):BrainV2Intent { if(this.hasAny(t,["planifie","planifier","organise","organiser","planning"]))return "plan"; if(this.hasAny(t,["objectif","atteindre","je veux","mon but"]))return "goal"; if(this.hasAny(t,["decide","decider","choisir","compare","meilleur choix"]))return "decision"; if(this.hasAny(t,["rendez-vous","agenda","calendrier","demain","semaine"]))return "schedule"; if(this.hasAny(t,["entreprise","chantier","client","devis","facture"]))return "business"; if(this.hasAny(t,["souviens","memoire","rappelle-moi","rappelle moi"]))return "memory"; if(this.hasAny(t,["projet","version","developper","construire"]))return "project"; if(t.includes("?"))return "question"; return "other"; }
 private detectDomains(t:string):BrainV2Domain[]{ const d=new Set<BrainV2Domain>(); if(this.hasAny(t,["rose","ia","app","application","v9","v8"]))d.add("rose"); if(this.hasAny(t,["entreprise","chantier","client","devis","facture","couverture","charpente"]))d.add("business"); if(this.hasAny(t,["maison","immobilier","notaire","vendeur","achat immobilier"]))d.add("property"); if(this.hasAny(t,["pret","banque","credit","budget","argent","finance"]))d.add("finance"); if(this.hasAny(t,["agenda","calendrier","rendez-vous","planning","demain"]))d.add("agenda"); if(this.hasAny(t,["tache","action","priorite"]))d.add("tasks"); if(this.hasAny(t,["apprendre","formation","comprendre","etudier"]))d.add("learning"); if(!d.size)d.add("general"); return [...d]; }
 private detectUrgency(t:string):BrainV2Urgency { if(this.hasAny(t,["urgence","urgent","immediatement","tout de suite"]))return "immediate"; if(this.hasAny(t,["rapidement","aujourd'hui","aujourdhui","demain"]))return "high"; if(this.hasAny(t,["plus tard","quand possible","pas urgent"]))return "low"; return "normal"; }
 private detectDates(t:string){ const r:string[]=[]; const n=t.match(/\b(?:0?[1-9]|[12]\d|3[01])[\/.-](?:0?[1-9]|1[0-2])(?:[\/.-]\d{2,4})?\b/g); if(n)r.push(...n); const l=t.toLowerCase(); ["aujourd'hui","demain","apres-demain","cette semaine","ce mois"].forEach(x=>{if(l.includes(x))r.push(x)}); return [...new Set(r)]; }
 private extractKeywords(t:string){ const s=new Set(["avec","dans","pour","mais","plus","tout","cette","comme","veux","faire","peux","peut","nous","vous","elle","rose","mon","mes","une","des","les","que","qui","sur","est"]); return [...new Set(t.split(/[^a-z0-9-]+/i).filter(w=>w.length>=4&&!s.has(w)))].slice(0,12); }
 private confidence(i:BrainV2Intent,d:BrainV2Domain[]){ let s=.55; if(i!=="other")s+=.2; if(!(d.length===1&&d[0]==="general"))s+=.15; return Math.min(.95,s); }
 private hasAny(t:string,terms:string[]){ return terms.some(x=>t.includes(x)); }
}
